# Generated by Django 5.0.6 on 2024-05-18 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostWatchedVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('published_data', models.DateTimeField(default=datetime.datetime(2024, 5, 18, 22, 54, 54, 435423))),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
